
[package]
name = "kas_vis"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "vis_core",
    "kas_grpc"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
